### ISSUE TITLE
1.0.6 failed on CRUK and TruSightMyeloid

### ISSUE THREAD

**Issue by mbyvcm** [AWGL/IlluminaQC#4] opened 2019-05-31 09:58 UTC
We have reverted back to 1.0.5 - we have not located the specific issue

**Comment by smrey** [comment] 2019-06-03 16:02
Issue caused by space at the bottom of the sample sheet resulting in the count of samples by this method being incorrect (increased by 1)- commas from csv counted as a sample name.
Fixed by not parsing lines starting with empty space or commas.

**Closed as completed by smrey** 2019-06-03 16:02 UTC
